modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
issueTrackerURL="https://github.com/hackedtogether/XPAdditions"

[[mods]]
modId="xpadditions"
version="${file.jarVersion}"
displayName="XP Additions"
displayURL="https://github.com/hackedtogether/XPAdditions"
logoFile="logo.png"
# credits="" #optional
authors="pd93, FullOfNull"
description='''
A little more experience.
'''

[[dependencies.xpadditions]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.xpadditions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
